(function(){
'use strict';
var CODES = Object.freeze({
  INVALID_MODE: 'INVALID_MODE',
  INVALID_BET: 'INVALID_BET',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  SPIN_IN_PROGRESS: 'SPIN_IN_PROGRESS',
  SPIN_NOT_ALLOWED: 'SPIN_NOT_ALLOWED',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  INVALID_RESULT: 'INVALID_RESULT',
  NETWORK_ERROR: 'NETWORK_ERROR',
  SYMBOLS_LOCKED: 'SYMBOLS_LOCKED',
  RTP_HARD_LIMIT: 'RTP_HARD_LIMIT',
  INVALID_MAX: 'INVALID_MAX',
  INVALID_MULTIPLIER: 'INVALID_MULTIPLIER',
  INVALID_GRID_SIZE: 'INVALID_GRID_SIZE',
  RNG_SYMBOL_NOT_FOUND: 'RNG_SYMBOL_NOT_FOUND',
  INVALID_WEIGHTS: 'INVALID_WEIGHTS'
});
function ApexError(code, message){
  var e = new Error(message || code);
  e.code = code;
  e.name = 'ApexError';
  return e;
}
window.ApexEngineErrors = Object.freeze({ CODES: CODES, ApexError: ApexError });
})();
