import { createEngineAdapter } from './ui/engine-adapter.js';

(function(){
  'use strict';
  const COLS=6, ROWS=5, TOTAL=30;
  const BETS=[0.2,0.5,1,2,3,5,10,15,20,30,50,100];
  const INITIAL_BALANCE=10000;
  const HISTORY_KEY='apex.sweet.session.v3';
  const LANG_KEY='apex.sweet.lang';
  const state={balance:INITIAL_BALANCE,betIndex:6,won:0,spinning:false,auto:0,autoLeft:0,turbo:false,history:[],adapter:null,sound:true,lang:'zh',reduced:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches||false,particles:[],raf:0,replay:false};
  let toastTimer=0, audioCtx=null;
  const $=id=>document.getElementById(id);
  const money=n=>Number(n||0).toFixed(2);
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const text={
    zh:{spin:'旋转',balance:'余额',win:'本局赢得',bet:'下注',auto:'自动',turbo:'快速',sound:'音效',pay:'赔付表',history:'记录',reset:'重置虚拟积分',help:'怎么玩',offline:'当前处于离线状态：本地虚拟积分模式仍可继续',online:'网络已恢复',free:'免费旋转',replay:'回放',language:'EN',ready:'准备好了吗？',complete:'完成',combo:'连消',bonus:'奖励回合',bomb:'炸弹倍率',session:'本次会话记录',noHistory:'还没有旋转记录。',replayEmpty:'暂无可回放局次。',virtual:'本版本仅使用浏览器虚拟积分，不连接支付、提现或真实货币系统。'},
    en:{spin:'SPIN',balance:'BALANCE',win:'WIN',bet:'BET',auto:'AUTO',turbo:'TURBO',sound:'Sound',pay:'Paytable',history:'History',reset:'Reset Credits',help:'How to play',offline:'Offline: local virtual-credit mode remains available',online:'Connection restored',free:'FREE SPINS',replay:'Replay',language:'中',ready:'READY?',complete:'COMPLETE',combo:'TUMBLE',bonus:'BONUS',bomb:'BOMB MULTIPLIER',session:'SESSION HISTORY',noHistory:'No spins recorded yet.',replayEmpty:'No replayable spins.',virtual:'Browser-only virtual credits. No deposits, withdrawals, or real-money wagering.'}
  };
  const t=k=>text[state.lang][k]||k;
  function toast(msg){const el=$('game-toast');if(!el)return;el.textContent=msg;el.classList.add('is-show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('is-show'),1800)}
  function haptic(pattern){if(navigator.vibrate&&!state.reduced){try{navigator.vibrate(pattern)}catch{}}}
  function ensureAudio(){if(!state.sound)return null;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audioCtx=audioCtx||new C();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}catch{return null}}
  function tone(freq,dur=.16,volume=.03,type='sine',when=0){const ctx=ensureAudio();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,ctx.currentTime+when);g.gain.setValueAtTime(.0001,ctx.currentTime+when);g.gain.exponentialRampToValueAtTime(volume,ctx.currentTime+when+.012);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+when+dur);o.connect(g).connect(ctx.destination);o.start(ctx.currentTime+when);o.stop(ctx.currentTime+when+dur+.02)}
  function audioCue(kind){if(!state.sound)return;const map={spin:[180],hit:[420,560],combo:[520,680,820],scatter:[420,660,920,1180],big:[520,740,980,1280],mega:[600,840,1100,1450],epic:[660,900,1200,1600,2000],free:[392,523,659,784]};(map[kind]||[340]).forEach((f,i)=>tone(f,.14,kind==='spin'?.018:.035,'sine',i*.045))}
  function buildBoard(){const b=$('game-board');b.innerHTML='';const frag=document.createDocumentFragment();for(let i=0;i<TOTAL;i++){const c=document.createElement('div');c.className='game-cell';c.dataset.idx=i;const h=document.createElement('div');h.className='game-cell__sym';c.appendChild(h);frag.appendChild(c)}b.appendChild(frag)}
  function paintGridWithIds(grid){const cells=document.querySelectorAll('.game-cell');const flat=(grid||[]).flat();for(let i=0;i<TOTAL;i++){const h=cells[i].querySelector('.game-cell__sym');h.innerHTML='';cells[i].classList.remove('is-empty','is-win','is-spinning','is-bomb','is-drop');cells[i].__symbolId=flat[i]||null;if(flat[i]){const node=window.ApexSweetSymbols?.build(flat[i],48);if(node)h.appendChild(node)}else cells[i].classList.add('is-empty')}}
  function markWins(ids){const set=new Set(ids||[]);document.querySelectorAll('.game-cell').forEach(c=>{c.classList.toggle('is-win',set.has(c.__symbolId));});if(set.size){haptic([12,20]);audioCue('hit')}}
  function update(){const bet=BETS[state.betIndex];$('game-balance').textContent=money(state.balance);$('game-won').textContent=money(state.won);$('game-bet').textContent=money(bet);$('game-auto').innerHTML=state.auto?`${t('auto')} <span>${state.autoLeft}</span>`:`${t('auto')} <span>10</span>`;$('game-auto').classList.toggle('is-on',!!state.auto);$('game-turbo').classList.toggle('is-on',state.turbo);$('game-sound').textContent=state.sound?'🔊':'🔇';$('game-spin-label').textContent=t('spin');$('game-mode').textContent=state.lang==='zh'?'练习模式 · 虚拟积分':'Practice · Virtual Credits';$('game-paytable').textContent=t('pay');$('game-history').textContent=t('history');$('game-reset').textContent=t('reset');$('game-help').setAttribute('aria-label',t('help'));$('game-lang').textContent=t('language');$('game-offline').hidden=navigator.onLine;}
  function tierClass(tier){return tier==='epic'?'is-epic':tier==='mega'?'is-super':tier==='big'?'is-mega':tier==='nice'?'is-big':''}
  function banner(amount,label,tier){const el=$('game-win-banner');$('win-label').textContent=label||t('win');$('win-amount').textContent=money(amount);el.className='game-win-banner';if(amount<=0)return;el.classList.add('is-show',tierClass(tier));audioCue(tier==='epic'?'epic':tier==='mega'?'mega':tier==='big'?'big':'hit');if(tier==='epic'||tier==='mega'){haptic([30,40,70]);burst(80)}else haptic(20)}
  function setBonus(n){const el=$('game-bonus');if(n>0){el.hidden=false;el.textContent=`${t('free')} ×${n}`}else el.hidden=true}
  function renderTumbleCount(n){$('game-tumble').textContent=n?`${t('combo')} ×${n}`:''}
  function burst(count=50){const canvas=$('fx-canvas');if(!canvas||state.reduced)return;const dpr=Math.min(window.devicePixelRatio||1,2);const rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const ctx=canvas.getContext('2d');if(!ctx)return;const max=Math.min(count,(navigator.deviceMemory&&navigator.deviceMemory<=2)?30:count);for(let i=0;i<max;i++){const a=(i/max)*Math.PI*2;const sp=1.2+(i%7)*.45;state.particles.push({x:rect.width/2,y:rect.height*.42,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp-1.5,life:1,size:2+(i%4),h:(i*37)%360})}if(!state.raf){const loop=()=>{state.raf=0;ctx.clearRect(0,0,rect.width*dpr,rect.height*dpr);ctx.save();ctx.scale(dpr,dpr);for(let i=state.particles.length-1;i>=0;i--){const p=state.particles[i];p.x+=p.vx*3;p.y+=p.vy*3;p.vy+=.05;p.life-=.025;if(p.life<=0){state.particles.splice(i,1);continue}ctx.globalAlpha=p.life;ctx.fillStyle=`hsl(${p.h} 90% 65%)`;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.restore();if(state.particles.length)state.raf=requestAnimationFrame(loop)};state.raf=requestAnimationFrame(loop)}}
  function normalizeReplay(view){return JSON.parse(JSON.stringify({grid:view.grid,finalGrid:view.finalGrid,totalWin:view.totalWin,winRatio:view.winRatio,tier:view.tier,scatterCount:view.scatterCount,tumbleCount:view.tumbleCount,tumbleSteps:view.tumbleSteps,freeSpinsAwarded:view.freeSpinsAwarded,freeSpins:view.freeSpins,bet:view.bet,mode:view.mode}))}
  function loadHistory(){try{const x=sessionStorage.getItem(HISTORY_KEY);return x?JSON.parse(x):[]}catch{return[]}}
  function saveHistory(){try{sessionStorage.setItem(HISTORY_KEY,JSON.stringify(state.history.slice(-12)))}catch{}}
  function addHistory(view,bet){state.history.push({at:new Date().toISOString(),bet,won:view.totalWin,ratio:view.winRatio,tumble:view.tumbleCount,freeSpins:view.freeSpinsAwarded,replay:normalizeReplay(view)});saveHistory()}
  async function animateDrop(from,to){if(state.reduced){paintGridWithIds(to);return}paintGridWithIds(from||to);document.querySelectorAll('.game-cell').forEach((c,i)=>{c.classList.add('is-drop');c.style.setProperty('--drop-delay',`${(i%COLS)*22}ms`)});await wait(state.turbo?90:260);paintGridWithIds(to);await wait(state.turbo?50:140)}
  async function animateResult(view){const steps=view.tumbleSteps||[];if(!steps.length){if(view.grid)paintGridWithIds(view.grid);return}for(let i=0;i<steps.length;i++){const step=steps[i];if(step.gridBefore)paintGridWithIds(step.gridBefore);renderTumbleCount(i+1);if(step.winIds?.length){markWins(step.winIds);await wait(state.turbo?130:420);const next=steps[i+1]?.gridBefore||view.finalGrid;await animateDrop(step.gridBefore,next);if(i>=2)burst(22);if(i+1>=3)audioCue('combo')}}if(view.finalGrid)await animateDrop(view.grid,view.finalGrid);renderTumbleCount(steps.length);}
  async function animateFreeSpins(fs){if(!fs||!fs.history?.length)return 0;setBonus(fs.spinsPlayed);audioCue('free');await wait(state.turbo?100:420);let total=0;for(let i=0;i<fs.history.length;i++){const h=fs.history[i];if(h.grid)paintGridWithIds(h.grid);$('game-tumble').textContent=`${t('bonus')} ${h.spin}/${fs.spinsPlayed}`;if(h.bombs?.length){const bomb=h.bombs.reduce((a,b)=>a+(b.multiplier||0),0);$('game-overlay-title').textContent=`${t('bomb')} +${bomb}×`;$('game-overlay').classList.add('is-show');audioCue('big');burst(55);haptic([25,30,25]);await wait(state.turbo?220:650);$('game-overlay').classList.remove('is-show')}else await wait(state.turbo?80:220);total+=h.spinWin||0}setBonus(0);return total}
  async function playView(view,opts={}){state.replay=!!opts.replay;paintGridWithIds(view.grid);await wait(state.turbo?100:300);await animateResult(view);if(!opts.skipFree)await animateFreeSpins(view.freeSpins);if(!opts.silent)banner(view.totalWin,view.freeSpinsAwarded?t('bonus')+' '+t('complete'):view.totalWin>0?t('win'):t('ready'),view.tier);state.replay=false}
  async function spin(){if(state.spinning||!state.adapter)return;const bet=BETS[state.betIndex];if(state.balance<bet){toast('虚拟积分不足，请重置');state.auto=0;return}state.spinning=true;state.balance-=bet;state.won=0;update();$('game-spin').disabled=true;document.querySelectorAll('.game-cell').forEach(c=>c.classList.add('is-spinning'));audioCue('spin');let result;try{result=state.adapter.playSpin(bet)}catch(e){console.error(e);state.balance+=bet;state.spinning=false;$('game-spin').disabled=false;toast('游戏引擎初始化失败');update();return}document.querySelectorAll('.game-cell').forEach(c=>c.classList.remove('is-spinning'));await playView(result.view);state.won=result.view.totalWin;state.balance+=result.view.totalWin;addHistory(result.view,bet);state.spinning=false;$('game-spin').disabled=false;update();if(state.auto){state.autoLeft--;if(state.autoLeft<=0){state.auto=0;update()}else setTimeout(spin,state.turbo?80:500)}}
  function changeBet(d){if(state.spinning)return;state.betIndex=clamp(state.betIndex+d,0,BETS.length-1);update()}
  function reset(){if(state.spinning)return;state.balance=INITIAL_BALANCE;state.won=0;state.history=[];state.auto=0;state.autoLeft=0;try{sessionStorage.removeItem(HISTORY_KEY);sessionStorage.removeItem('apex.sweet.history.v1')}catch{}update();toast('虚拟积分已重置')}
  function modal(html){$('game-modal-content').innerHTML=html;$('game-modal').hidden=false;document.body.classList.add('modal-open')}
  function closeModal(){$('game-modal').hidden=true;document.body.classList.remove('modal-open')}
  function openPaytable(){const list=window.ApexSweetSymbols?.list||[];let h=`<h2>${t('pay')}</h2><p class="modal-note">${state.lang==='zh'?'同类符号在任意位置达到 8 个即可中奖。':'8+ matching symbols anywhere can win.'}</p><div class="pay-grid">`;list.forEach(s=>{const art=window.ApexSweetSymbols.build(s.id,54);h+=`<div class="pay-item"><div class="pay-art">${art?art.outerHTML:''}</div><b>${s.name}</b><span>${s.m8||'Special'} · ${s.m10||'—'} · ${s.m12||'—'}</span></div>`});h+='</div>';modal(h)}
  async function replayItem(x){if(!x.replay){toast(t('replayEmpty'));return}closeModal();state.spinning=true;state.replay=true;$('game-spin').disabled=true;await playView(x.replay,{replay:true});state.replay=false;state.spinning=false;$('game-spin').disabled=false;update()}
  function openHistory(){let h=`<h2>${t('session')}</h2>`;if(!state.history.length){h+=`<p class="modal-note">${t('noHistory')}</p>`;modal(h);return}h+='<div class="history-list">';state.history.slice().reverse().forEach((x,i)=>{h+=`<div class="history-row"><span>#${state.history.length-i} · ${money(x.bet)}</span><b class="${x.won>0?'win':''}">${x.won>0?'+':''}${money(x.won)}</b><button class="replay-btn" data-replay="${state.history.length-1-i}">${t('replay')}</button></div>`});h+='</div>';modal(h);$('game-modal-content').querySelectorAll('[data-replay]').forEach(btn=>btn.addEventListener('click',()=>replayItem(state.history[Number(btn.dataset.replay)])))}
  function bind(){
    $('game-back').onclick=()=>history.length>1?history.back():location.href='index.html';
    $('bet-minus').onclick=()=>changeBet(-1);$('bet-plus').onclick=()=>changeBet(1);$('game-spin').onclick=spin;$('game-reset').onclick=reset;$('game-paytable').onclick=openPaytable;$('game-history').onclick=openHistory;$('game-modal-close').onclick=closeModal;$('game-modal').onclick=e=>{if(e.target===$('game-modal'))closeModal()};
    $('game-sound').onclick=()=>{state.sound=!state.sound;if(state.sound)audioCue('hit');update()};
    $('game-turbo').onclick=()=>{state.turbo=!state.turbo;update()};
    $('game-help').onclick=()=>modal(`<h2>${t('help')}</h2><p>${state.lang==='zh'?'点击旋转，6×5 盘面会进行糖果坠落。任意位置出现 8 个以上同类糖果即可中奖；中奖糖果消除后继续下落，形成连消。':'Spin the 6×5 grid. 8+ matching symbols anywhere can win; wins tumble away and refill for chained cascades.'}</p><p>${state.lang==='zh'?'4 个以上 Scatter 进入免费旋转，奖励回合中的炸弹倍率会累积。':'4+ Scatter trigger Free Spins; bomb multipliers accumulate during the bonus.'}</p><p class="modal-note">${t('virtual')}</p>`);
    $('game-auto').onclick=()=>{if(state.spinning)return;if(state.auto){state.auto=0;state.autoLeft=0}else{state.auto=1;state.autoLeft=10;spin()}update()};
    $('game-lang').onclick=()=>{state.lang=state.lang==='zh'?'en':'zh';try{localStorage.setItem(LANG_KEY,state.lang)}catch{}update();toast(state.lang==='zh'?'已切换中文':'English enabled')};
    document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!state.spinning){e.preventDefault();spin()}if(e.key==='Escape')closeModal()});
    window.addEventListener('online',()=>{update();toast(t('online'));});window.addEventListener('offline',()=>{update();toast(t('offline'));});
  }
  async function init(){
    while(!window.ApexSweetSymbols)await wait(20);
    buildBoard();
    let config;try{const r=await fetch('/config/game.json',{cache:'no-store'});if(!r.ok)throw Error('config '+r.status);config=await r.json()}catch(e){toast('配置加载失败，请检查网络或刷新');throw e}
    state.adapter=createEngineAdapter(config,{mode:'demo'});state.history=loadHistory();
    try{state.lang=localStorage.getItem(LANG_KEY)||'zh'}catch{}
    $('game-spin-label').textContent=t('spin');
    paintGridWithIds(state.adapter.previewGrid());bind();update();
    if(!navigator.onLine)toast(t('offline'));
  }
  init().catch(e=>console.error(e));
})();
