/* 轮盘 · 音效 */
(function(){
'use strict';
var ctx=null,master=null,comp=null,dryGain=null,enabled=true,VOL=0.7;
function init(){if(ctx)return true;try{var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;ctx=new AC();master=ctx.createGain();master.gain.value=VOL;comp=ctx.createDynamicsCompressor();comp.threshold.value=-18;comp.knee.value=12;comp.ratio.value=4;comp.attack.value=.003;comp.release.value=.25;master.connect(comp);comp.connect(ctx.destination);dryGain=ctx.createGain();dryGain.gain.value=.9;dryGain.connect(master);return true;}catch(e){return false;}}
function now(){return ctx?ctx.currentTime:0;}
function ping(freq,dur,vol,when,type){if(!enabled||!ctx)return;var t=when!=null?when:now();var o=ctx.createOscillator(),g=ctx.createGain();o.type=type||'sine';o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol||.25,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(dryGain);o.start(t);o.stop(t+dur+.05);}
function fm(c,m,idx,dur,vol,when){if(!enabled||!ctx)return;var t=when!=null?when:now();var co=ctx.createOscillator(),mo=ctx.createOscillator(),mg=ctx.createGain(),g=ctx.createGain();co.type='sine';co.frequency.value=c;mo.type='sine';mo.frequency.value=m;mg.gain.value=c*idx;mo.connect(mg);mg.connect(co.frequency);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(vol||.22,t+.003);g.gain.exponentialRampToValueAtTime(.0001,t+dur);co.connect(g);g.connect(dryGain);mo.start(t);co.start(t);mo.stop(t+dur+.03);co.stop(t+dur+.03);}
function noise(dur,vol,when,centerF,Q){if(!enabled||!ctx)return;var t=when!=null?when:now();var len=Math.floor(ctx.sampleRate*dur);var buf=ctx.createBuffer(1,len,ctx.sampleRate);var d=buf.getChannelData(0);var rnd=new Uint32Array(len);crypto.getRandomValues(rnd);for(var i=0;i<len;i++)d[i]=(rnd[i]/2147483648-1)*(1-i/len);var src=ctx.createBufferSource();src.buffer=buf;var f=ctx.createBiquadFilter();f.type='bandpass';f.frequency.value=centerF||2400;f.Q.value=Q||2;var g=ctx.createGain();g.gain.value=vol||.15;src.connect(f);f.connect(g);g.connect(dryGain);src.start(t);}
var _spinTimer=null;
function spinStart(durMs){if(!enabled||!ctx)return;var t=now();noise(durMs/1000*0.9,.07,t,500,1);if(_spinTimer){clearInterval(_spinTimer);_spinTimer=null;}var start=Date.now();var tickCount=0;_spinTimer=setInterval(function(){if(!enabled)return;var el=Date.now()-start;if(el>durMs){clearInterval(_spinTimer);_spinTimer=null;return;}tickCount++;var v=.14*(1-el/durMs*0.7);ping(2400-(el/durMs)*800+(tickCount%4)*60,.04,v,null,'sine');},100);}
function spinStop(){if(_spinTimer){clearInterval(_spinTimer);_spinTimer=null;}}
var API={init:init,enabled:function(v){if(v===undefined)return enabled;enabled=!!v;if(master&&ctx)master.gain.setTargetAtTime(enabled?VOL:0,ctx.currentTime,.03);return enabled;},click:function(){if(!ctx)init();ping(3200,.04,.14);},chip:function(){if(!ctx)init();var t=now();fm(2800,900,3,.05,.15,t);ping(2000,.06,.1,t+.02);},spinStart:spinStart,spinStop:spinStop,ballSettle:function(){if(!ctx)init();var t=now();ping(1800,.08,.15,t);ping(1400,.12,.12,t+.06);ping(1100,.18,.1,t+.12);},win:function(){if(!ctx)init();var t=now();[784,988,1175,1568].forEach(function(f,i){ping(f,.35,.11,t+i*.08,'sine');});},bigWin:function(){if(!ctx)init();var t=now();noise(.5,.15,t,800,1);[523,659,784,1047,1319,1568,2093].forEach(function(f,i){ping(f,.4,.12,t+i*.07);});},lose:function(){if(!ctx)init();var t=now();ping(440,.12,.09,t);ping(330,.18,.08,t+.1);}};
window.RouletteAudio=API;
})();
